# Based on https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml
baseURL: "https://veerendra2.github.io"
title: Veerendra's Blog
paginate: 5
theme: "PaperMod-6.0"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: "UA-112970252-1"

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 0
        - identifier: search
          name: Search
          url: /search/
          weight: 0
        # - identifier: about
        #   name: About
        #   url: /about/
        #   weight: 0

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "My Blog"
  author: Veerendra K
  defaultTheme: dark
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  tocopen: true
  comments:
    provider: giscus
    commentable:
      page: true
      post: true
    giscus:
      repo: veerendra2/veerendra2.github.io
      repo_id: MDEwOlJlcG9zaXRvcnkxMTU4MjE4OTE=
      category: General
      category_id: MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyODQwMzM5
      mapping: url
      label: comment
      theme: dark_tritanopia
      reactions_enabled: 0

  editPost:
    URL: "https://github.com/veerendra2/veerendra2.github.io/issues/new?assignees=veerendra2&labels=bug&template=suggest-changes.md&title=%5BCHANGE%5D"
    Text: "Suggest Changes"

  homeInfoParams:
    Title: "Hi There"
    Content: Welcome to my blog...

  socialIcons:
    - name: "github"
      url: "https://github.com/veerendra2"
    - name: "gitlab"
      url: "https://gitlab.com/veerendrav2"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/veerendrav2"
    - name: "cv"
      url: "/Resume_Blog.pdf"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/2200798/veerendra"
    - name: "twitter"
      url: "https://twitter.com/remark6205"
    - name: medium
      url: "https://medium.com/@cursor9401"
    # - name: "steam"
    #   url: "<link2>"

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    # noClasses: false
    style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
