languageCode: "en-us"
baseUrl: ""
title: "Veerendra's Blog"
theme: "hugo-PaperMod-6.0"
paginate: 10
googleAnalytics: "UA-112970252-1"
enableRobotsTXT: true

menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 0
    - identifier: search
      name: Search
      url: /search/
      weight: 0
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 0

params:
  author: "Veerendra K"
  homeInfoParams:
    Title: Hi There
    Content: Welcome to my blog
  dateFormat: "02-01-2006"
  paginationSinglePost: true
  style: dark
  ShowReadingTime: true
  copyCodeButton: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  # utteranc.es support
  utterancesRepo: "" # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # isso support
  isso:
    enabled: true # mandatory
    data: "https://comments.example.com/" # mandatory
    jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
    css: true # optional
    lang: "en" # optional
    replyToSelf: true # mandatory
    requireAuthor: true # mandatory
    requireEmail: true # mandatory
    id: "thread-id" # optional
    avatar: true # optional
    avatar-bg: "#f0f0f0" # optional
    feed: false # optional

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/veerendrav2"
    # - name: "cv"
    #   url: "<link2>"
    - name: "github"
      url: "https://github.com/veerendra2"
    - name: "gitlab"
      url: "https://gitlab.com/veerendrav2"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/2200798/veerendra"
    - name: "twitter"
      url: "https://twitter.com/remark6205"
    # - name: "steam"
    #   url: "<link2>"
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
