name: Hugo Site
on:
  push:
    branches:
      - source
  workflow_dispatch:

env:
  BUILD_IMAGE: ghcr.io/veerendra2/veerendra2.github.io/hugo:0.102.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source branch
        uses: actions/checkout@v2
        with:
          ref: "source"
          path: "source"

      - name: Build site
        run: |
          docker run \
            -v ${{ github.workspace }}:/opt/ \
            -v ${{ github.workspace }}/public:/opt/public \
            $BUILD_IMAGE /bin/bash -c "pushd /opt/ && hugo --debug"

      - name: Cloning master branch
        uses: actions/checkout@v2
        with:
          ref: "master"
          path: "master"

      - name: Copying _site content to master branch repo
        run: cp -R ${{ github.workspace }}/source/public/* ${{ github.workspace }}/master

      - name: Commit files
        run: |
          cd ${{ github.workspace }}/master
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "New changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ github.workspace }}/master
          branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
